Added support for Google Translation API
mbi/django-rosetta pull request #222
Opened 2019-05-31 15:18 UTC by martinsvoboda

Added support for Google Translation API. By my experience Google provides better translations than Microsoft Azure.  Nowadays Google API v3 provides translation up to 500 000 characters for free. See https://cloud.google.com/translate/pricing

Sorry I do not know, how to mock and test Google API package.

### All Submissions:

- [ ] Are tests passing? (From the root-level of the repository please run `pip install tox && tox`)
- [ ] I have added or updated a test to cover the changes proposed in this Pull Request
- [x] I have updated the documentation to cover the changes proposed in this Pull Request

2020-06-03 12:12 UTC, bittner requested changes

2020-06-03 12:12 UTC, bittner commented on rosetta/translate_utils.py
> +        # }
This should probably go into a docstring of a function that returns the result. Or, even better, into a unit test.

2020-06-03 12:12 UTC, bittner commented on rosetta/translate_utils.py
> +            # https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-translate?tabs=curl
Same here: Put it into the docstring of the function that returns the response. And/or put it into test code.

2020-06-03 12:12 UTC, bittner commented on rosetta/translate_utils.py
> +    # using new v3beta Translation API
Can you add a docstring to the `translate_by_google` function and move that information there? This will provide more value than a comment.

2020-06-03 12:12 UTC, bittner commented on rosetta/translate_utils.py
> +    else:
Can we simplify this code? The `else` is likely unnecessary here. While this is technically correct many developers are confused by it. There is no change in the business logic if we omit the `else`, is it?

2020-06-03 12:12 UTC, bittner commented on rosetta/views.py
> +
3 empty lines violates PEP8. This empty line should be removed.

2021-02-18 16:13 UTC, izimobil commented
@martinsvoboda , @bittner , @mbi : Do you need some help with PR ? I'd like it to be merged :)

2021-03-04 14:03 UTC, merged

2021-03-04 14:04 UTC, mbi commented
Thanks again and sorry for sitting on this so long :shrug:

2021-03-04 14:07 UTC, mbi commented
PS: tried mocking the Google Translation API, couldn't get it to work without providing a valid credentials JSON file, gave up.