Add Azerbaijani language support
mbi/django-rosetta pull request #284
Opened 2024-01-20 15:37 UTC by vusallyv

### All Submissions:

- [ ] Are tests passing? (From the root-level of the repository please run `pip install tox && tox`)
- [ ] I have added or updated a test to cover the changes proposed in this Pull Request
- [ ] I have updated the documentation to cover the changes proposed in this Pull Request

2024-04-25 08:34 UTC, nemoralis requested changes

2024-04-25 08:34 UTC, nemoralis commented on rosetta/locale/az/LC_MESSAGES/django.po
> +msgstr "Proyekt"
We have "layihə" in Azerbaijani for this word. "Proyekt" is not a common (ümumişlək) word

2024-04-25 08:34 UTC, nemoralis commented on rosetta/locale/az/LC_MESSAGES/django.po
> +msgstr "Proqress"
This should be "Proqres"

2024-04-25 08:34 UTC, nemoralis commented on rosetta/locale/az/LC_MESSAGES/django.po
> +msgstr "ProqressI %(percent_translated)s%%"
This should be "Proqres"

2024-06-23 13:30 UTC, vusallyv commented
@mbi could you please review this PR too?

2024-06-23 13:46 UTC, mbi commented
I was kinda hoping you would address @nemoralis' comments above. I can't judge how pertinent they are and was hoping you guys come to an agreement on what the better translations would be? :pray:

2024-06-23 13:50 UTC, vusallyv commented
I have corrected the translation based on the change requests of @nemoralis.

2024-06-23 14:10 UTC, merged

2024-06-23 14:10 UTC, mbi commented
Ah yes, so you did, thank you!

2024-06-23 14:11 UTC, vusallyv commented
Welcome!