Fix deepl variable translation issue 276
mbi/django-rosetta pull request #290
Opened 2024-06-10 12:49 UTC by halitcelik

### All Submissions:

- [x] Are tests passing? (From the root-level of the repository please run `pip install tox && tox`)
- [x] I have added or updated a test to cover the changes proposed in this Pull Request
- [x] I have updated the documentation to cover the changes proposed in this Pull Request

2024-06-10 12:50 UTC, halitcelik commented
#276

2024-06-11 14:56 UTC, mbi requested changes

2024-06-11 14:56 UTC, mbi commented on rosetta/translate_utils.py
> +            if variable and type_specifier:
can we please test using this syntax:
```xml
<var type="s">name</var>
```

2024-06-11 14:56 UTC, mbi commented on rosetta/translate_utils.py
> +def format_text(text, direction="to_deepl"):
If possible, move this or rename this function

2024-06-11 14:56 UTC, mbi commented on rosetta/translate_utils.py
> +    if direction == "to_deepl":
check that different formats are supported.

2024-10-07 10:04 UTC, mbi commented
Merged via 6139629

2024-10-07 10:04 UTC, closed without merging